import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Herosection from '../components/Herosection';

import Navbar1 from '../components/Navbar1';
import Navbar2 from '../components/Navbar2';
import Newcollection from '../components/Newcollection';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Good Furnitures </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar1/>
      <Navbar2/>
      <Herosection/>
      <Newcollection/>
     
    </div>
  );
}
